# -*- coding: utf-8 -*-
"""Welcome to Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Install necessary libraries
!pip install --upgrade diffusers transformers -q

# Import libraries
import os
import torch
import tqdm
import numpy as np
import pandas as pd
from pathlib import Path
from PIL import Image
import matplotlib.pyplot as plt
from diffusers import StableDiffusionPipeline
from transformers import pipeline, set_seed

# Define the image generation function
def create_image_from_text(description, diffusion_model):
    """
    Generate an image based on the provided text prompt using a diffusion model.

    :param description: Text description to generate the image.
    :param diffusion_model: Pre-trained Stable Diffusion model.
    :return: Generated image.
    """
    settings = {
        "steps": 9,
        "guidance": 7.5,
        "size": (512, 512)
    }

    generated_image = diffusion_model(
        description,
        num_inference_steps=settings["steps"],
        guidance_scale=settings["guidance"]
    ).images[0]

    return generated_image.resize(settings["size"])

# Example usage
if __name__ == "__main__":
    # Initialize the model (assuming you have loaded or defined `diffusion_model` somewhere)
    diffusion_model = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")

    # Generate an image
    image = create_image_from_text("A vibrant sunset over a mountain range", diffusion_model)

    # Display the image
    plt.imshow(image)
    plt.axis('off')
    plt.show()

    # Save the image
    image.save("generated_image.png")